# Generated by Django 4.1.4 on 2023-01-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationproduct',
            old_name='quottion_id',
            new_name='quotation_id',
        ),
    ]
