# Generated by Django 4.1.4 on 2023-01-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_alter_quotation_valid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='Creation_Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
