# Generated by Django 4.1.4 on 2023-01-18 03:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_alter_quotationproduct_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationproduct',
            name='Total_Price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='quotationproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
    ]
