# Generated by Django 4.1.5 on 2023-01-23 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_manager_finance'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseOrder',
            fields=[
                ('PO_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Valid_Date', models.DateField(max_length=6, null=True)),
                ('Creation_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Finance_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.finance')),
                ('seller_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.seller')),
            ],
        ),
    ]
