# Generated by Django 4.1.5 on 2023-01-25 17:36

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseOrder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='Finance_ID',
            new_name='finance_ID',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='Purchaseorder_Number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='Seller_Address',
            field=models.TextField(default='Some', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='Seller_Name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('description', models.TextField(max_length=60)),
                ('proposed_quantity', models.IntegerField()),
                ('selected_quantity', models.IntegerField(blank=True, null=True)),
                ('Total_Price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('purchaseorder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseOrder.purchaseorder')),
            ],
        ),
    ]
