# Generated by Django 4.1.5 on 2023-01-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseOrder', '0002_rename_finance_id_purchaseorder_finance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='Seller_Address',
            field=models.TextField(max_length=100),
        ),
    ]
