# Generated by Django 4.1.5 on 2023-01-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseOrder', '0005_alter_purchaseorder_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='Quotation_Number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
